module.exports = {
  purge: {
    content: [
      "./pages/**/*.{js,ts,jsx,tsx}",
      "./src/components/**/*.{js,ts,jsx,tsx}",
    ],
    safelist: [
      "flex-col",
      "flex-row",
      "justify-center",
      "justify-between",
      "justify-start",
      "justify-end",
      "items-center",
      "items-start",
      "items-end",
      "space-x-1",
      "space-x-2",
      "space-x-3",
      "space-x-4",
      "space-x-5",
      "space-x-6",
      "space-x-7",
      "space-x-8",
      "space-x-10",
      "space-y-1",
      "space-y-2",
      "space-y-3",
      "space-y-4",
      "space-y-5",
      "space-y-6",
      "space-y-7",
      "space-y-8",
      "space-y-10",
      "text-text",
      "text-body",
      "text-primary",
      "text-accent",
      "text-header",
      "text-md",
      "text-lg",
      "text-xl",
      "text-2xl",
      "text-3xl",
      "text-4xl",
      "text-5xl",
      "font-bold",
      "font-extrabold",
      "uppercase",
      "grid-cols-1",
      "grid-cols-2",
      "grid-cols-3",
      "grid-cols-4",
      "grid-cols-5",
      "gap-0",
      "gap-1",
      "gap-2",
      "gap-3",
      "gap-4",
      "gap-5",
      "gap-6",
      "gap-7",
      "gap-8",
      "gap-10",
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        primary: "#05944F",
        accent: "#1E54B7",
        body: "#ffffff",
        header: "#1F1F1F",
        text: "#545454",
      },
      fontSize: {
        xxs: "0.6875rem",
      },
      height: {
        ["120"]: 472,
      },
    },
    fontFamily: {
      sans: ["Inter", "sans-serif"],
      roboto: ["Roboto", "sans-serif"],
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
